[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "t_alpha"
requires-python = "~= 3.10.0"
version = "0.1.1"

dependencies = [
    "aiohappyeyeballs==2.4.4",
    "aiohttp==3.11.10",
    "aiosignal==1.3.2",
    "attrs==24.3.0",
    "black==24.10.0",
    "certifi==2024.12.14",
    "charset-normalizer==3.4.0",
    "click==8.1.7",
    "colorama==0.4.6",
    "contourpy==1.3.1",
    "cycler==0.12.1",
    "filelock==3.16.1",
    "fonttools==4.55.3",
    "frozenlist==1.5.0",
    "fsspec==2024.10.0",
    "h5py==3.12.1",
    "idna==3.10",
    "Jinja2==3.1.4",
    "joblib==1.4.2",
    "keopscore==2.2.3",
    "kiwisolver==1.4.7",
    "lightning-utilities==0.11.9",
    "MarkupSafe==3.0.2",
    "matplotlib==3.10.0",
    "mpmath==1.3.0",
    "multidict==6.1.0",
    "mypy-extensions==1.0.0",
    "networkx==3.4.2",
    "numpy==2.2.0",
    "packaging==24.2",
    "pandas==2.2.3",
    "pathspec==0.12.1",
    "pillow==11.0.0",
    "platformdirs==4.3.6",
    "propcache==0.2.1",
    "psutil==6.1.0",
    "pybind11==2.13.6",
    "pykeops==2.2.3",
    "pyparsing==3.2.0",
    "python-dateutil==2.9.0.post0",
    "pytorch-lightning==2.4.0",
    "pytz==2024.2",
    "PyYAML==6.0.2",
    "requests==2.32.3",
    "scikit-learn==1.6.0",
    "scipy==1.14.1",
    "six==1.17.0",
    "sympy==1.13.1",
    "threadpoolctl==3.5.0",
    "torch==2.5.1",
    "torch-cluster==1.6.3",
    "torch-geometric==2.6.1",
    "torchmetrics==1.6.0",
    "tqdm==4.67.1",
    "typing_extensions==4.12.2",
    "tzdata==2024.2",
    "urllib3==2.2.3",
    "yarl==1.18.3",
    # TODO bring in alphabetic oder
    "biopandas~=0.5",
    "biopython~=1.81",
    "colorlog~=6.8",
    "openbabel-wheel~=3.1",
    "pyarrow~=18.1",
    "pydantic~=2.7",
    "py3Dmol~=2.4",
    "python-json-logger~=2.0",
    "rdkit~=2023.9.3,<2024.09.4",
    # "scikit-learn==1.4.0", # for compatibility with scaler pickle files
    "smart-open[gcs]~=7.1",
    "torch-cluster~=1.6",
    "zstandard~=0.23",
]

[project.entry-points."console_scripts"]
inference = "t_alpha.scripts.inference:main"
gen_hdf5 = "t_alpha.scripts.gen_hdf5:main"
mc_dropout = "t_alpha.scripts.mc_dropout:main"
train = "t_alpha.scripts.train:main"

[tool.setuptools.packages.find]
where = ["src/"]
include = [
  "t_alpha.*"
]

[tool.setuptools.package-data]
"t_alpha.resources" = ["*.pkl", "*.json.zst"]
